# Generated by Django 3.0.3 on 2020-02-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerPolicy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='Cover',
            field=models.IntegerField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
