# Generated by Django 3.0.3 on 2020-02-28 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerPolicy', '0002_policy_cover'),
        ('createCustomer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAssociate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createCustomer.Customer')),
                ('PolicyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerPolicy.Policy')),
            ],
        ),
    ]
